import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Loop studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div className="w-screen">
        <body>{children}</body>
      </div>
    </html>
  );
}
